import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

export type MemoryEntry = {
  id?: string;
  author?: string;
  source: string;
  text: string;
  createdAt?: string;
};

export type MemoryAtom = {
  id: string;
  author: string;
  source: string;
  createdAt: string;
  summary: string;
  evidence: string;
  themes: string[];
  tags: string[];
};

export type MemoryTheme = {
  name: string;
  summary: string;
  atoms: string[];
};

export type ProgressiveContext = {
  themes: Array<{ name: string; summary: string }>;
  atoms: Array<{ id: string; summary: string; evidence: string; themes: string[] }>;
  graph: {
    nodes: Array<{ id: string; type: "theme" | "atom"; label: string }>;
    edges: Array<{ from: string; to: string; relation: "contains" | "related" }>;
  };
};

const DEFAULT_THEME_KEYWORDS: Record<string, string[]> = {
  triage: ["triage", "intake", "ticket", "request", "queue"],
  escalation: ["escalate", "urgent", "blocked", "risk", "priority"],
  approval: ["approve", "approved", "review", "confirm", "yes"],
  customer_data: ["email", "customer", "contact", "phone", "address"],
  workflow: ["workflow", "process", "sequence", "steps", "handoff"],
  policy: ["rule", "policy", "must", "always", "never"],
  learning: ["learn", "teach", "remember", "correct", "update"],
};

export async function ensureRoomStructure(roomPath: string): Promise<void> {
  await mkdir(join(roomPath, "raw"), { recursive: true });
  await mkdir(join(roomPath, "atoms"), { recursive: true });
  await mkdir(join(roomPath, "themes"), { recursive: true });

  const indexPath = join(roomPath, "index.md");
  const graphPath = join(roomPath, "graph.json");

  await writeFile(
    indexPath,
    "# Room memory\n\nThis file is generated by the memory compiler.\n",
    "utf8",
  );

  await writeFile(
    graphPath,
    JSON.stringify({ nodes: [], edges: [] }, null, 2),
    "utf8",
  );
}

export function normalizeText(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

export function summarizeText(text: string): string {
  const clean = normalizeText(text);
  if (clean.length <= 200) {
    return clean;
  }

  return `${clean.slice(0, 197).trimEnd()}...`;
}

export function inferThemes(text: string): string[] {
  const lowered = text.toLowerCase();
  const matches = Object.entries(DEFAULT_THEME_KEYWORDS)
    .filter(([, keywords]) => keywords.some((keyword) => lowered.includes(keyword.toLowerCase())))
    .map(([theme]) => theme);

  return matches.length > 0 ? matches : ["general"];
}

export function createAtom(entry: MemoryEntry): MemoryAtom {
  const id = entry.id ?? `atom-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const createdAt = entry.createdAt ?? new Date().toISOString();
  const summary = summarizeText(entry.text);
  const themes = inferThemes(entry.text);

  return {
    id,
    author: entry.author ?? "unknown",
    source: entry.source,
    createdAt,
    summary,
    evidence: normalizeText(entry.text),
    themes,
    tags: themes,
  };
}

async function writeAtomFile(atomPath: string, atom: MemoryAtom): Promise<void> {
  const content = `---\nid: ${atom.id}\nauthor: ${atom.author}\nsource: ${atom.source}\ncreated_at: ${atom.createdAt}\nthemes:\n  - ${atom.themes.join("\n  - ")}\n---\n\n${atom.evidence}\n`;
  await writeFile(atomPath, content, "utf8");
}

async function writeThemeFile(themePath: string, themeName: string, atoms: MemoryAtom[]): Promise<void> {
  const summary = `${themeName} (${atoms.length} atom${atoms.length === 1 ? "" : "s"}) — ${atoms
    .slice(0, 3)
    .map((atom) => atom.summary)
    .join("; ")}`;

  const content = `---\ntheme: ${themeName}\nsummary: ${summary}\natoms:\n${atoms.map((atom) => `  - ${atom.id}`).join("\n")}\n---\n\n${atoms
    .map((atom) => `- ${atom.id}: ${atom.summary}`)
    .join("\n")}\n`;

  await writeFile(themePath, content, "utf8");
}

export async function compileRoomMemory(roomPath: string, entries: MemoryEntry[]): Promise<MemoryTheme[]> {
  await ensureRoomStructure(roomPath);

  const atoms = entries.map(createAtom);
  const themeMap = new Map<string, MemoryAtom[]>();

  for (const atom of atoms) {
    for (const theme of atom.themes) {
      const existing = themeMap.get(theme) ?? [];
      existing.push(atom);
      themeMap.set(theme, existing);
    }
  }

  const themeEntries: MemoryTheme[] = [];

  for (const [themeName, themeAtoms] of themeMap) {
    const theme: MemoryTheme = {
      name: themeName,
      summary: `${themeName} (${themeAtoms.length} atoms)`,
      atoms: themeAtoms.map((atom) => atom.id),
    };

    themeEntries.push(theme);
    const themeFilePath = join(roomPath, "themes", `${themeName}.md`);
    await writeThemeFile(themeFilePath, themeName, themeAtoms);
  }

  for (const atom of atoms) {
    const atomPath = join(roomPath, "atoms", `${atom.id}.md`);
    await writeAtomFile(atomPath, atom);
  }

  const graph = {
    nodes: [
      ...themeEntries.map((theme) => ({ id: `theme:${theme.name}`, type: "theme" as const, label: theme.name })),
      ...atoms.map((atom) => ({ id: `atom:${atom.id}`, type: "atom" as const, label: atom.summary })),
    ],
    edges: [
      ...atoms.flatMap((atom) =>
        atom.themes.map((themeName) => ({
          from: `theme:${themeName}`,
          to: `atom:${atom.id}`,
          relation: "contains" as const,
        })),
      ),
    ],
  };

  const indexLines = ["# Theme map\n"];
  for (const theme of themeEntries) {
    indexLines.push(`## ${theme.name}`);
    indexLines.push(`- summary: ${theme.summary}`);
    indexLines.push(`- atoms: ${theme.atoms.join(", ")}`);
    indexLines.push("");
  }

  await writeFile(join(roomPath, "index.md"), indexLines.join("\n"), "utf8");
  await writeFile(join(roomPath, "graph.json"), JSON.stringify(graph, null, 2), "utf8");

  return themeEntries;
}

export async function buildProgressiveContext(
  roomPath: string,
  query: string,
  options: { limitThemes?: number; limitAtoms?: number } = {},
): Promise<ProgressiveContext> {
  const limitThemes = options.limitThemes ?? 5;
  const limitAtoms = options.limitAtoms ?? 5;

  const atomDir = join(roomPath, "atoms");
  const themeDir = join(roomPath, "themes");

  const atomFiles = await readdir(atomDir).catch(() => []);
  const themeFiles = await readdir(themeDir).catch(() => []);

  const atoms = await Promise.all(
    atomFiles
      .filter((file) => file.endsWith(".md"))
      .map(async (file) => {
        const content = await readFile(join(atomDir, file), "utf8");
        const match = content.match(/---\n([\s\S]*?)---\n\n([\s\S]*)/);
        if (!match) {
          return null;
        }

        const frontmatter = match[1];
        const body = match[2].trim();
        const target = frontmatter.split("\n").reduce<Record<string, string>>((acc, line) => {
          const separator = line.indexOf(": ");
          if (separator === -1) return acc;
          const key = line.slice(0, separator).trim();
          const value = line.slice(separator + 2).trim();
          acc[key] = value;
          return acc;
        }, {});

        return {
          id: target.id ?? file.replace(/\.md$/, ""),
          author: target.author ?? "unknown",
          source: target.source ?? "unknown",
          createdAt: target.created_at ?? new Date().toISOString(),
          summary: summarizeText(body),
          evidence: normalizeText(body),
          themes: (frontmatter.match(/-\s+([^\n]+)/g) ?? []).map((matchText) => matchText.replace(/^-\s+/, "")),
        };
      }),
  );

  const validAtoms = atoms.filter(Boolean) as Array<{
    id: string;
    author: string;
    source: string;
    createdAt: string;
    summary: string;
    evidence: string;
    themes: string[];
  }>;

  const graphRaw = await readFile(join(roomPath, "graph.json"), "utf8").catch(() => "{\"nodes\":[],\"edges\":[]}");
  const graph = JSON.parse(graphRaw);

  const queryLower = query.toLowerCase();
  const scoredThemes = themeFiles
    .filter((file) => file.endsWith(".md"))
    .map((file) => ({
      file,
      score: file.toLowerCase().includes(queryLower) ? 2 : 0,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limitThemes)
    .map(async ({ file }) => {
      const content = await readFile(join(themeDir, file), "utf8");
      const lineMatch = content.match(/theme:\s*(.+)/);
      const summaryMatch = content.match(/summary:\s*(.+)/);
      return {
        name: lineMatch?.[1]?.trim() ?? file.replace(/\.md$/, ""),
        summary: summaryMatch?.[1]?.trim() ?? "Theme summary unavailable",
      };
    });

  const themes = (await Promise.all(scoredThemes)).slice(0, limitThemes);

  const rankedAtoms = validAtoms
    .map((atom) => ({
      atom,
      score:
        (atom.summary.toLowerCase().includes(queryLower) ? 3 : 0) +
        atom.themes.filter((theme) => queryLower.includes(theme.toLowerCase())).length,
    }))
    .sort((a, b) => b.score - a.score)
    .slice(0, limitAtoms)
    .map(({ atom }) => ({
      id: atom.id,
      summary: atom.summary,
      evidence: atom.evidence,
      themes: atom.themes,
    }));

  return {
    themes,
    atoms: rankedAtoms,
    graph,
  };
}

export async function createExampleRoom(roomPath: string): Promise<void> {
  await ensureRoomStructure(roomPath);

  const entries: MemoryEntry[] = [
    {
      id: "atom-1",
      author: "ren",
      source: "slack",
      text: "When the ticket is missing the customer email, do not guess. Ask for the email first and mark the request as pending.",
    },
    {
      id: "atom-2",
      author: "david",
      source: "slack",
      text: "Escalate any blocked request when the customer has not replied within 24 hours or the issue risk is high.",
    },
    {
      id: "atom-3",
      author: "ren",
      source: "slack",
      text: "Every workflow run should confirm the human approval before posting a side effect.",
    },
  ];

  await compileRoomMemory(roomPath, entries);
}
