import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

export type MemoryEntry = {
  id?: string;
  author?: string;
  source: string;
  text: string;
  createdAt?: string;
  themes?: string[];
};

export type MemoryAtom = {
  id: string;
  author: string;
  source: string;
  createdAt: string;
  summary: string;
  evidence: string;
  themes: string[];
  tags: string[];
};

export type MemoryTheme = {
  name: string;
  summary: string;
  atoms: string[];
};

export type ProgressiveContext = {
  themes: Array<{ name: string; summary: string }>;
  atoms: Array<{
    id: string;
    author: string;
    source: string;
    summary: string;
    evidence: string;
    themes: string[];
  }>;
  graph: {
    nodes: Array<{ id: string; type: "theme" | "atom"; label: string }>;
    edges: Array<{ from: string; to: string; relation: "contains" | "related" }>;
  };
};

const DEFAULT_THEME_KEYWORDS: Record<string, string[]> = {
  triage: ["triage", "intake", "ticket", "request", "queue"],
  escalation: ["escalate", "urgent", "blocked", "risk", "priority"],
  approval: ["approve", "approved", "review", "confirm", "yes"],
  customer_data: ["email", "customer", "contact", "phone", "address"],
  workflow: ["workflow", "process", "sequence", "steps", "handoff"],
  policy: ["rule", "policy", "must", "always", "never"],
  learning: ["learn", "teach", "remember", "correct", "update"],
};

/** Atom ids and theme names become filenames, and both can originate in Slack text. */
function toSafeName(value: string, fallback: string): string {
  const safe = value
    .replace(/[^A-Za-z0-9._-]+/g, "-")
    .replace(/^[.\-]+/, "")
    .replace(/-{2,}/g, "-")
    .slice(0, 120);

  return safe.length > 0 ? safe : fallback;
}

function splitDocument(content: string): { frontmatter: string; body: string } {
  const match = content.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) {
    return { frontmatter: "", body: content.trim() };
  }

  return { frontmatter: match[1], body: match[2].trim() };
}

/** Handles the two shapes we write: `key: value` scalars and `key:` followed by `  - item` lists. */
function parseFrontmatter(frontmatter: string): {
  scalars: Record<string, string>;
  lists: Record<string, string[]>;
} {
  const scalars: Record<string, string> = {};
  const lists: Record<string, string[]> = {};
  let openList: string | null = null;

  for (const line of frontmatter.split("\n")) {
    if (line.trim().length === 0) continue;

    const item = line.match(/^\s+-\s*(.*)$/);
    if (item && openList) {
      const value = item[1].trim();
      if (value.length > 0) lists[openList].push(value);
      continue;
    }

    const field = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!field) continue;

    const [, key, value] = field;
    if (value.trim().length > 0) {
      scalars[key] = value.trim();
      openList = null;
    } else {
      openList = key;
      lists[key] = [];
    }
  }

  return { scalars, lists };
}

export function normalizeText(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

export function summarizeText(text: string): string {
  const clean = normalizeText(text);
  if (clean.length <= 200) {
    return clean;
  }

  return `${clean.slice(0, 197).trimEnd()}...`;
}

export function inferThemes(text: string): string[] {
  const lowered = text.toLowerCase();
  const matches = Object.entries(DEFAULT_THEME_KEYWORDS)
    .filter(([, keywords]) => keywords.some((keyword) => lowered.includes(keyword.toLowerCase())))
    .map(([theme]) => theme);

  return matches.length > 0 ? matches : ["general"];
}

export function createAtom(entry: MemoryEntry): MemoryAtom {
  const fallbackId = `atom-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const id = toSafeName(entry.id ?? fallbackId, fallbackId);
  const createdAt = entry.createdAt ?? new Date().toISOString();
  const evidence = normalizeText(entry.text);
  const explicit = (entry.themes ?? []).map((theme) => toSafeName(theme, "general"));
  const themes = explicit.length > 0 ? explicit : inferThemes(evidence);

  return {
    id,
    author: entry.author ?? "unknown",
    source: entry.source,
    createdAt,
    summary: summarizeText(evidence),
    evidence,
    themes,
    tags: themes,
  };
}

async function writeIfMissing(path: string, content: string): Promise<void> {
  try {
    await readFile(path, "utf8");
  } catch {
    await writeFile(path, content, "utf8");
  }
}

/** Creates the room layout without touching anything already there — atoms are append-only. */
export async function ensureRoomStructure(roomPath: string): Promise<void> {
  await mkdir(join(roomPath, "raw"), { recursive: true });
  await mkdir(join(roomPath, "atoms"), { recursive: true });
  await mkdir(join(roomPath, "themes"), { recursive: true });

  await writeIfMissing(
    join(roomPath, "index.md"),
    "# Room memory\n\nThis file is generated by the memory compiler.\n",
  );

  await writeIfMissing(join(roomPath, "graph.json"), `${JSON.stringify({ nodes: [], edges: [] }, null, 2)}\n`);
}

async function writeAtomFile(atomPath: string, atom: MemoryAtom): Promise<void> {
  const themes = atom.themes.length > 0 ? atom.themes : ["general"];
  const themeLines = themes.map((theme) => `  - ${theme}`).join("\n");
  const content = `---\nid: ${atom.id}\nauthor: ${atom.author}\nsource: ${atom.source}\ncreated_at: ${atom.createdAt}\nthemes:\n${themeLines}\n---\n\n${atom.evidence}\n`;
  await writeFile(atomPath, content, "utf8");
}

async function writeThemeFile(themePath: string, themeName: string, atoms: MemoryAtom[]): Promise<void> {
  const summary = `${themeName} (${atoms.length} atom${atoms.length === 1 ? "" : "s"}) — ${atoms
    .slice(0, 3)
    .map((atom) => atom.summary)
    .join("; ")}`;

  const content = `---\ntheme: ${themeName}\nsummary: ${summary}\natoms:\n${atoms
    .map((atom) => `  - ${atom.id}`)
    .join("\n")}\n---\n\n${atoms.map((atom) => `- ${atom.id} (${atom.author}): ${atom.summary}`).join("\n")}\n`;

  await writeFile(themePath, content, "utf8");
}

/** Reads the atoms already committed to a room. The atom files are the source of truth. */
export async function readAtoms(roomPath: string): Promise<MemoryAtom[]> {
  const atomDir = join(roomPath, "atoms");
  const files = (await readdir(atomDir).catch(() => [])).filter((file) => file.endsWith(".md"));

  const atoms = await Promise.all(
    files.map(async (file) => {
      const content = await readFile(join(atomDir, file), "utf8").catch(() => "");
      const { frontmatter, body } = splitDocument(content);
      const evidence = normalizeText(body);
      if (evidence.length === 0) return null;

      const { scalars, lists } = parseFrontmatter(frontmatter);
      const themes = lists.themes?.length ? lists.themes : inferThemes(evidence);

      return {
        id: scalars.id ?? file.replace(/\.md$/, ""),
        author: scalars.author ?? "unknown",
        source: scalars.source ?? "unknown",
        createdAt: scalars.created_at ?? new Date(0).toISOString(),
        summary: summarizeText(evidence),
        evidence,
        themes,
        tags: themes,
      } satisfies MemoryAtom;
    }),
  );

  return atoms
    .filter((atom): atom is MemoryAtom => atom !== null)
    .sort((a, b) => a.createdAt.localeCompare(b.createdAt) || a.id.localeCompare(b.id));
}

/**
 * Compiles `entries` into the room. Atoms already on disk survive — a correction adds knowledge,
 * it never wipes what the channel taught earlier. `themes/`, `index.md`, and `graph.json` are
 * regenerated from the full set, so they always describe every atom present.
 */
export async function compileRoomMemory(roomPath: string, entries: MemoryEntry[]): Promise<MemoryTheme[]> {
  await ensureRoomStructure(roomPath);

  const incoming = entries.map(createAtom);
  const byId = new Map<string, MemoryAtom>();
  for (const atom of await readAtoms(roomPath)) byId.set(atom.id, atom);
  for (const atom of incoming) byId.set(atom.id, atom);

  const atoms = [...byId.values()].sort(
    (a, b) => a.createdAt.localeCompare(b.createdAt) || a.id.localeCompare(b.id),
  );

  for (const atom of incoming) {
    await writeAtomFile(join(roomPath, "atoms", `${atom.id}.md`), atom);
  }

  const themeMap = new Map<string, MemoryAtom[]>();
  for (const atom of atoms) {
    for (const theme of atom.themes) {
      const existing = themeMap.get(theme) ?? [];
      existing.push(atom);
      themeMap.set(theme, existing);
    }
  }

  const themeEntries: MemoryTheme[] = [];
  const themeDir = join(roomPath, "themes");
  const written = new Set<string>();

  for (const [themeName, themeAtoms] of [...themeMap].sort(([a], [b]) => a.localeCompare(b))) {
    themeEntries.push({
      name: themeName,
      summary: `${themeName} (${themeAtoms.length} atom${themeAtoms.length === 1 ? "" : "s"})`,
      atoms: themeAtoms.map((atom) => atom.id),
    });

    const fileName = `${toSafeName(themeName, "general")}.md`;
    written.add(fileName);
    await writeThemeFile(join(themeDir, fileName), themeName, themeAtoms);
  }

  // Themes are derived, so a theme no atom claims any more is stale and must not linger.
  const stale = (await readdir(themeDir).catch(() => [])).filter(
    (file) => file.endsWith(".md") && !written.has(file),
  );
  for (const file of stale) {
    await rm(join(themeDir, file), { force: true });
  }

  const graph = {
    nodes: [
      ...themeEntries.map((theme) => ({ id: `theme:${theme.name}`, type: "theme" as const, label: theme.name })),
      ...atoms.map((atom) => ({ id: `atom:${atom.id}`, type: "atom" as const, label: atom.summary })),
    ],
    edges: atoms.flatMap((atom) =>
      atom.themes.map((themeName) => ({
        from: `theme:${themeName}`,
        to: `atom:${atom.id}`,
        relation: "contains" as const,
      })),
    ),
  };

  const indexLines = ["# Theme map", ""];
  for (const theme of themeEntries) {
    indexLines.push(`## ${theme.name}`);
    indexLines.push(`- summary: ${theme.summary}`);
    indexLines.push(`- atoms: ${theme.atoms.join(", ")}`);
    indexLines.push("");
  }

  await writeFile(join(roomPath, "index.md"), indexLines.join("\n"), "utf8");
  await writeFile(join(roomPath, "graph.json"), `${JSON.stringify(graph, null, 2)}\n`, "utf8");

  return themeEntries;
}

function queryTerms(query: string): string[] {
  return normalizeText(query)
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((term) => term.length > 2);
}

function scoreText(text: string, terms: string[]): number {
  const lowered = text.toLowerCase();
  return terms.filter((term) => lowered.includes(term)).length;
}

/**
 * Layer 1 is the generated theme list, layer 2 atom summaries, layer 3 the exact evidence.
 * Themes are ranked by the atoms that claim them, not by their filename. With no usable query
 * terms this degrades to the most recent atoms, which is the "last N" behaviour we want.
 */
export async function buildProgressiveContext(
  roomPath: string,
  query: string,
  options: { limitThemes?: number; limitAtoms?: number } = {},
): Promise<ProgressiveContext> {
  const limitThemes = options.limitThemes ?? 5;
  const limitAtoms = options.limitAtoms ?? 5;
  const terms = queryTerms(query);

  const atoms = await readAtoms(roomPath);

  const graphRaw = await readFile(join(roomPath, "graph.json"), "utf8").catch(() => "");
  let graph: ProgressiveContext["graph"] = { nodes: [], edges: [] };
  try {
    const parsed = JSON.parse(graphRaw);
    if (Array.isArray(parsed?.nodes) && Array.isArray(parsed?.edges)) graph = parsed;
  } catch {
    // A malformed or missing graph is recoverable — recompiling the room regenerates it.
  }

  const atomScores = new Map<string, number>();
  for (const atom of atoms) {
    const score = scoreText(atom.evidence, terms) * 2 + atom.themes.reduce((total, theme) => total + scoreText(theme, terms), 0);
    atomScores.set(atom.id, score);
  }

  const themeDir = join(roomPath, "themes");
  const themeFiles = (await readdir(themeDir).catch(() => [])).filter((file) => file.endsWith(".md"));

  const themeDocs = await Promise.all(
    themeFiles.map(async (file) => {
      const content = await readFile(join(themeDir, file), "utf8").catch(() => "");
      const { scalars } = parseFrontmatter(splitDocument(content).frontmatter);
      const name = scalars.theme ?? file.replace(/\.md$/, "");
      const claimed = atoms.filter((atom) => atom.themes.includes(name));
      const score =
        scoreText(name, terms) * 2 +
        claimed.reduce((total, atom) => total + (atomScores.get(atom.id) ?? 0), 0);

      return { name, summary: scalars.summary ?? `${name} (${claimed.length} atoms)`, score };
    }),
  );

  const themes = themeDocs
    .sort((a, b) => b.score - a.score || a.name.localeCompare(b.name))
    .slice(0, limitThemes)
    .map(({ name, summary }) => ({ name, summary }));

  const rankedAtoms = [...atoms]
    .sort(
      (a, b) =>
        (atomScores.get(b.id) ?? 0) - (atomScores.get(a.id) ?? 0) ||
        b.createdAt.localeCompare(a.createdAt),
    )
    .slice(0, limitAtoms)
    .map((atom) => ({
      id: atom.id,
      author: atom.author,
      source: atom.source,
      summary: atom.summary,
      evidence: atom.evidence,
      themes: atom.themes,
    }));

  return { themes, atoms: rankedAtoms, graph };
}

export async function createExampleRoom(roomPath: string): Promise<void> {
  await ensureRoomStructure(roomPath);

  const entries: MemoryEntry[] = [
    {
      id: "atom-1",
      author: "ren",
      source: "slack",
      createdAt: "2026-09-12T18:00:00.000Z",
      text: "When the ticket is missing the customer email, do not guess. Ask for the email first and mark the request as pending.",
    },
    {
      id: "atom-2",
      author: "david",
      source: "slack",
      createdAt: "2026-09-12T18:05:00.000Z",
      text: "Escalate any blocked request when the customer has not replied within 24 hours or the issue risk is high.",
    },
    {
      id: "atom-3",
      author: "ren",
      source: "slack",
      createdAt: "2026-09-12T18:10:00.000Z",
      text: "Every workflow run should confirm the human approval before posting a side effect.",
    },
  ];

  await compileRoomMemory(roomPath, entries);
}
